#!/bin/sh -e

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
RED='\033[1;31m'
NC='\033[0m'

SYSTEM_TYPE="aarch64-darwin"
FLAKE_SYSTEM="darwinConfigurations.${SYSTEM_TYPE}.system"

export NIXPKGS_ALLOW_UNFREE=1

echo "${YELLOW}Updating ONLY Safe Inputs (Skipping core Nixpkgs)...${NC}"
nix flake update \
  brew-api \
  brew-nix \
  darwin \
  home-manager \
  homebrew-bundle \
  homebrew-cask \
  homebrew-core \
  nix-homebrew 

echo "${YELLOW}Starting build...${NC}"
nix build .#$FLAKE_SYSTEM $@

echo "${YELLOW}Switching to new generation...${NC}"
./result/sw/bin/darwin-rebuild switch --flake .#${SYSTEM_TYPE} $@

echo "${YELLOW}Cleaning up...${NC}"
unlink ./result

# I assume there's no mise config in this repo or it may not work.
echo "${YELLOW} Install and upgrade MISE managed tools"
if [ -n "$SUDO_USER" ]; then
    sudo -u "$SUDO_USER" mise install
    sudo -u "$SUDO_USER" mise upgrade --bump
else
    mise install
    mise upgrade --bump
fi

echo "${GREEN}Switch to new generation complete!${NC}"

nix store gc
