_:

[
  "1password"
  "adobe-digital-editions"
  "alacritty"
  "android-studio"
  "appcleaner"
  "brave-browser"
  "brave-browser@beta"
  "caffeine"
  "calibre"
  # Find out how
  # "canon-ufrii-driver"
  "charles"
  "chatgpt"
  # Slow install
  "coconutbattery"
  "disk-drill"
  "firefox"
  "firefox@developer-edition"
  "floorp"
  "github@beta"
  "google-chrome"
  "google-chrome@beta"
  "google-chrome@canary"
  "google-drive"
  "handbrake"
  "hiddenbar"
  "iina"
  "keka"
  "kindle-previewer"
  "logi-options-plus"
  "macs-fan-control"
  "microsoft-edge"
  "mullvad-browser"
  "nordlayer"
  "nordvpn"
  "notunes"
  "obsidian"
  "ollama"
  "ollamac"
  "pgadmin4"
  "porting-kit"
  "postman"
  "protonvpn"
  "raycast"
  "rectangle"
  "signal"
  "slack"
  "spotify"
  "tailscale"
  "teamviewer"
  "temurin"
  "telegram"
  "the-unarchiver"
  "ui"
  "upscayl"
  "utm"
  "visual-studio-code"
  "vlc"
  "vysor"
  "wine-stable"
  # "wine@staging"
  "wireshark"
  "xquartz"
  "yam-display"
  # "zenmap"

  # "homebrew/cask/docker"
  # "syncthing"
  # "raycast"
]
