import = ["./alacritty_dracula.toml"]

#[shell]
#program = "/run/current-system/sw/bin/zsh"
#args = ["--login"]

#working_directory = "<string>" | "None"

[window]
padding = { x = 24, y = 24 }
# Set to transparent and you will lose tab setup
decorations = "full"
opacity = 0.7
blur = true
decorations_theme_variant = "Dark"
resize_increments = true
option_as_alt = "Both"

[scrolling]
history = 100000

[font]
size = 12

[bell]
animation = "EaseOutCirc"
duration = 50
color = "#FF0000"

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "On" }

[keyboard]
bindings = [
   { key = "Space", mods = "Command|Shift", mode = "~Search", action = "ToggleViMode" },
   { key = "Space", mods = "Command|Shift", mode = "Vi|~Search", action = "ScrollToBottom" },
]
